### ISSUE TITLE
Documentation is lacking

### ISSUE THREAD

**Issue by Aversiste** [Deveryware/ansible-haproxy#14]
In order to write a proper configuration for a moderately complex install I had to reverse-engineer the templates. Documentation for the various templates would be a plus.

I see separate wiki pages for `defaults`, `frontend`, `global`, `listen`,  `resolvers` and `userlist` as good vessels.

What do you think?

**Comment by Aversiste** [comment]
First page about the defaults section: https://github.com/Deveryware/ansible-haproxy/wiki/defaults

**Comment by olo-dw** [comment]
This issue is a never ending story. What kind of definition of done do you expected?

**Comment by Aversiste** [comment]
I want to document the current state of role for the release 1.3.0.

**Comment by Aversiste** [comment]
The wiki now currently reflects the state of this role. A lot more can be improved but this is good enough to close this issue.
